### ISSUE TITLE
Case - Timeline

### ISSUE THREAD

**Issue by robertocarroll** [robertocarroll/icc-beta#29]
Prototype here: 
http://robertocarroll.com/icc-alpha/timeline/lubanga.html

**Comment by robertocarroll** [comment]
Haven't resolved the issue with linking directly to a slide before the user engages with the timeline.

**Comment by robertocarroll** [comment]
![01-04_case](https://cloud.githubusercontent.com/assets/1565953/4310062/c1cce8ee-3ea2-11e4-8130-69e76a83dee6.jpg)

**Comment by robertocarroll** [comment]
Is it OK for this to be JSON for ICC Beta or do we want to build a tool within Sharepoint to create the JSON?

**Comment by taslaman** [comment]
I believe we need to have data from a list/library in JSON format. This
doesn't have to be a high priority, but it needs to be done, as my
understanding is that we will go from Beta to Release Candidate quite
rapidly.

**Comment by robertocarroll** [comment]
There's still the issue around the key development links not working until the user initialises the timeline.

To recreate the issue: 
1. Go to: https://github.com/NUKnightLab/TimelineJS3
2. Click on one of the links in the key developments, e.g. Transfer to The Hague
3. The url hash value changes but the timeline state does not.
4. Click on a point in the timeline 
5. Try clicking on a link in key developments now and the timeline goes to the correct point. 

Here's the old ICC Alpha issue exploring different possible fixes: https://github.com/robertocarroll/icc-alpha/issues/72 

Also there's a new version of the timeline under development: https://github.com/NUKnightLab/TimelineJS3 which has the required functionality but it's not clear when it will be ready for use in a live environment.

**Comment by simmigaba** [comment]
As discussed earlier in e-mail, I have created a new SP List (Timeline) - http://sharepoint13vm.cloudapp.net/sites/icc/drc/lubanga/Lists/Timeline/AllItems.aspx at Case site level. This list will contain data for Timeline. In the Timeline WebPart, it will read data from this SP list and will generate the JSON object dynamically.

The Structure of Timeline SP list is as below:

![image](https://cloud.githubusercontent.com/assets/5706403/5612509/28ec4934-94fc-11e4-8ee6-692baba2b1d9.png)

**Comment by simmigaba** [comment]
As discussed with Armin in various e-mail chains before, the below features are implemented for Timeline:
1. A Timeline SP list is created at case site level which will have info about Timeline JSON object. This list will be populated by Content Creators and have below structure. The data is populated for Lubanga Timeline SP list which can be used as a reference - http://sharepoint13vm.cloudapp.net/sites/icc/drc/lubanga/Lists/Timeline/AllItems.aspx

![image](https://cloud.githubusercontent.com/assets/5706403/6390295/fcd6549a-bdd0-11e4-9be7-c4c83e8bcb22.png)
1. Each row in above SP list should have values for Timeline Start Date, Timeline Headline, Timeline Tag and Timeline Text. Optionally for Media, the columns Timeline Asset Media, Timeline Credit and Timeline Caption may have value. The column TimelineType will contain value as "default" only for one row in the SP list which will correspond to header entry in JSON object.
2. The above SP list also has columns as KeyDev (Yes/ No) and KeyDevTitle. These values will be populated only for those JSON object entries that we want to display in Key developments section on Case Page. Base on these, automatically the Key developments section will be generated and will have links to the Timeline. Hence there is no need to manually create/ update Key developments section anymore.
3. A custom SharePoint list workflow is created on above SP list so that whenever any JSON object entry is updated/ created, automatically it will generate a new JSON file (json.txt, DocumentType = 'JSON') in SP library "Documents" at Case site level. This is the file from which Timeline loads the JSON object  data. Hence there is no need to manually create or update JSON object file anymore.
4. Once the custom SharePoint list workflow automatically generates the JSON file (json.txt), its possible to validate if JSON is valid using online JSON validator e.g. http://jsonlint.com/

The issue around the key development links not working until the user initializes the timeline still persists. This issue will be tracked separately as part of leftover tasks.
