### ISSUE TITLE
Case - News and summaries

### ISSUE THREAD

**Issue by robertocarroll** [robertocarroll/icc-beta#34]
![01-02_case](https://cloud.githubusercontent.com/assets/1565953/4310977/11034f54-3eab-11e4-882b-91e733e18f75.jpg)
- Users did not know the difference between "news" (press releases) and "announcements" (shorter, more frequent updates - like Twitter posts). Visual distinction?
- Confirm that the featured slot on the left can be used by all content types, e.g. press release, court record, video, etc.

**Comment by erikaORC** [comment]
Perhaps the "news" and "announcements" do not have to be separate sections at all.  One "newsfeed" that displays the latest press releases and announcements in one location might be less confusing for users.

**Comment by simmigaba** [comment]
![image](https://cloud.githubusercontent.com/assets/5706403/5727985/edbab296-9b8c-11e4-80b2-818b93a39608.png)

![image](https://cloud.githubusercontent.com/assets/5706403/5728085/a5e3560c-9b8d-11e4-944a-9f53b9636625.png)

Armin - As I recall from alpha Phase, The Featured story section for Case Page i.e. snapshot below can be anything i.e. it can be Press Release, can have Video, Image, Summary Text etc. Therefore I believe best to create Featured Story section is to have a content Editor Web Part which Content Creators can modify accordingly i.e. they can create custom content and can link to external YouTube Video or to content in AV Gallery, etc. I am not sure if we can have Featured story part auto generated from underlying SP list or library as it can be anything like Image, Video, Text, etc. What do you think?

![image](https://cloud.githubusercontent.com/assets/5706403/5728169/3f15984e-9b8e-11e4-82a0-e23fa0f24e12.png)

**Comment by robertocarroll** [comment]
Please can you clarify the "featured" story:
https://cloud.githubusercontent.com/assets/5706403/5728169/3f15984e-9b8e-11e4-82a0-e23fa0f24e12.png

It is the ability to "feature" some kind of content, which might be a video or it might be something else, i.e. not necessarily a video. So it is showing the most important thing to a user in that case at the time. 

Is that how everyone else understood it?

**Comment by simmigaba** [comment]
Yes Rob I have the same understanding. This section is showing the most important thing to user in that case at the time and can be Video, Podcast, Image, Text, Link to document or whatever. That's why I want to leave this section as simple HTML Content Editor WebPart which Content Administrators can directly modify as and when need arises. Because for this section we can not have a pre-decided data fields/ structure in the underlying SP list/library nor can have pre-defined logic e.g. fetch and display latest Press Release etc.
So I was just looking for confirmation from Armin that if he is happy to manage the Featured Story section as simple HTML Content Editor WebPart going way forward. And not to have any SP data structure and programmatic logic for same.

**Comment by robertocarroll** [comment]
Sorry Simmi - I missed your paragraph between the red text and the YouTube image. All makes sense.

**Comment by simmigaba** [comment]
Featured Story in now a Content Editor Web Part which fetches content to display from case-featured-story.html present in Pages Library at Case Site level. In future the content can be modified accordingly.
