### ISSUE TITLE
Case - Court records

### ISSUE THREAD

**Issue by robertocarroll** [robertocarroll/icc-beta#35]
![01-03_case](https://cloud.githubusercontent.com/assets/1565953/4423575/0da6b980-4596-11e4-914a-82d68f9388c5.jpg)

**Comment by simmigaba** [comment]
As mentioned in one of the e-mail communications before, the data migration from list and libraries of existing website to list and libraries in new website will be a big project in itself as the data structures are very different between the two and the mapping is NOT 1:1 between the corresponding list and library fields. Moreover data might need some translation or transformation before we migrate it. Once data is properly migrated to new website, then stuff like Transcript title etc will automatically be mapped properly as all this info comes from underlying list and libraries of new website.

**Comment by simmigaba** [comment]
The web parts developed during alpha phase to display Court records and Transcripts have to be modified to fetch data from centralized document libraries (as per the discussion happening around design and requirements of Court records management system).

Also it might be its good to divide this issue into two issues -- "Case - Court records" and "Case Transcripts" so that I can later move these tasks separately to Sprint backlog for coding and completion. Rob - Pls suggest.

**Comment by robertocarroll** [comment]
I've renamed this issue and created a new issue for Case - Transcripts #68 and split the card into two cards in Trello.

**Comment by simmigaba** [comment]
Additional requirement to:
-- fetch the data from new centralized document libraries for CRM module
-- display the latest version of Court Record (i.e. latest Corrigenda or latest Redaction or Original document if published after Redaction) in case multiple versions of same Court Record exists
-- Always show the language of the current site if Court Record in that language is available. If not show the original language

**Comment by simmigaba** [comment]
As per requirements of new CRM module, below functionality is implemented and tested for this web part:
1. Fetch latest Court Records from centralized Court Records library ordered by Sequence number (Descending) based on match on Case Name.
2. Fetch only latest Court records i.e. latest Corrigenda for a given Sequence number or latest Redaction (or Original) for a given Sequence number
3. Display number of Court records as per configurable web part property. At the moment property value is set to 3. 
4. Display the latest Court Record in the site language i.e. if latest Corrigenda is available in both English and French then display the English record if site language is English otherwise display French
5. If latest Court Record is only available in other language then display the same i.e. if latest Corrigenda is only available in French then display the French record if site language is English
6. Display all the latest Court  records from Parent Case if the Case has Parent Case (i.e. scenario of Case Split or Case Name change). To display Court records from Parent case, again Points 1-5 above are applicable. 
7. Display all the latest Court  records from Child Cases if the Case is created after Merging other Cases (i.e. scenario of Case A and Case B Merged into Case C). To display Court records from Child cases, again Points 1-5 above are applicable. 
8. The Web part also has another configurable property which takes value as "CourtRecords" or "Transcripts" based on which either latest CourtRecords or Transcripts are displayed. For this webpart set property as "CourtRecords".

![image](https://cloud.githubusercontent.com/assets/5706403/5332060/fdf9e452-7e6c-11e4-94ba-10d42bf6069e.png)
