### ISSUE TITLE
Court records management system

### ISSUE THREAD

**Issue by robertocarroll** [robertocarroll/icc-beta#41]
Thread to keep track of the potential ICC Court Records management system for ICC Beta.

Initial proposal is here: https://www.dropbox.com/s/yfkfgworyqpjehg/ICC%20website%20Court%20Records%20management%20system.docx?dl=0

Perhaps you could update this thread with the responses from email so we don't lose track? Thanks!

**Comment by simmigaba** [comment]
For Tracking, Updating the E-mail exchange:

---

Dear Simmi. I would suggest the following:
1.       Create the Court Records Management System in the main Site Collection. The original idea came from http://blogs.technet.com/b/tothesharepoint/archive/2013/02/14/how-to-set-up-a-product-centric-web-site-in-sharepoint-2013.aspx. I thought of separating data and libraries from the front-facing website, so it would be easier to maintain.
2.       We need to have a Record Center as it will serve as central collection point, metadata correction, alert system for PIDS for some documents that cannot be routed due to the problems in the metadata, and routing solution for court records coming from TRIM.
3.        As for the way of automation of the upload and metadata insertion, I would leave this to ICT, as they are experts in this. I was under the impression, that we will be able to move all court records, old and new, to the new website (case by case) in batches. For the initial content load-up we can use TRIM, but if e-Filing would be better for the future, then by all means, we should use that after we get all the old records on the website.
4.       All below mentioned web parts can be used, but they cannot use static pages as results, as court records will be displayed by the use of display templates and page templates, which you have pointed below.
5.       Centralized library – I did not mean to have one library for all court records, and I apologize if I presented it that way. My idea was to create a Records Center which would be connected to libraries (one per case/situation).
I believe I covered all your questions. If I did not, please let me know.
Thank you very much on this, as I can now see much clearly this new module and really the core of the website.
Kind regards,

## Armin.

Dear Armin,
I have reviewed the solution proposal for "ICC Website Court Records Management System". Before moving on to my queries (later part of this email), I wanted to brief you on what we have already developed as part of alpha so you can comment on what needs to stay and what needs to be changed.
Currently in alpha site, we have Court Records document library at each Situation and Case level where user can upload the Court Records and associated metadata. Three custom web parts were developed for managing court records in alpha phase:
ü  Court Record Index Web part that displays latest 2 or 3 court records for a specific Situation or Case page. This list is fetched from the Court Records document library specific to that Situation/Case. This webpart also has a "More" button which re-directs to Global Index and Search web part (explained later) containing filters for metadata which are pre-selected for that specific Situation/Case.
ü  Court Record Web part to show individual court record details. When user clicks on Court record Title link from above Index web part, the content on this web part is generated dynamically based on the metadata stored in Court Record library, also a link is generated to download the Court record pdf. As you already know in current web site this is a cumbersome process as you need to create Court Record page and manually enter the metadata in iccdcos as well as in pages library at situation/case level. The idea was to automate the process as much as possible and eliminate redundancy of data.
ü  ​Global Index and Search Web part to display court records from all Situations and Cases. User can filter the results based on pre-defined filters (if arriving here from a particular Situation/Case) or can manually specify search criteria. The result for this web part is generated by fetching content from Court Record libraries present in all Situations and Cases subsites.

As mentioned before, when user clicks on "More" button in the Court Record Index web part (1st web part above) on any Situation/Case page, the control is re-directed to above Global Index and Search web part but with filtered results i.e. Situation and/or Case value is pre-populated in the drop downs and records are displayed accordingly.
Now based on your solution proposal, we need to further modify the content type of document libraries and look and feel of above web parts. E.g. for Court Record web part showing individual court record details, we also want to show related documents links, etc. Modifying these web parts and content type is not an issue from technical and implementation perspective.
Mainly I want to clarify below listed design points. Please let me know if I am not clear enough.
1.       Records Center or central library for uploading Court records documents - Though we can define this centralized library but then do we really need Court Records library at each Situation and Case level?
   If Yes, then what purpose would it solve? All 3 web parts described above (Global Index and Search Web part, Court Record Index Web part and Court Record web part) can be modified to fetch content from this central library simply by filtering on meta data columns whose value will be passed from website page context i.e. based on request originated from which Situation/Case page, etc.
   So I am trying to understand the real requirement to have Court Record document libraries at all Situation/Case levels as then we also have to develop additional workflows as you described to synch the content from Records Center to Situation and Case specific libraries.
2.       What is the real advantage of having two separate site collections - one for content i.e. Court Records document libraries and other for actual sites? In new website, most of the data so far is and would be generated dynamically using web parts and we don't have static ASPX pages for court records any more as these pages are generated dynamically. So ideally its really a content site collection that we have already setup in alpha.
3.       My understanding is that all the "public" Court records and associated metadata will be uploaded automatically from TRIM to new site using an Integration solution between TRIM and SharePoint which will synch the new Court Records or any updates to Court Records from TRIM to Sharepoint either at scheduled intervals or based on certain events.

Alternate solution is integration between new e-Filing system (which uploads Court records and metadata to TRIM) and Sharepoint. But e-Filing system does not have old Court Records and metadata i.e. data before e-Filing system went live last year.

Also I am not sure whether users would still be manually uploading Court Records and metadata in public website or would it only be coming automatically via integration bridge between TRIM and Sharepoint.

Please correct me if my understanding regarding the integration requirement is wrong and if you could please provide more details and further thoughts on this.
Once these  points are clarified, then I believe implementing the other low level requirements and design features mentioned in your proposal document should not be an issue.
I will accordingly provide the effort estimates for overall development work for this module.
Thanks
Kind Regards
Simmi

**Comment by simmigaba** [comment]
The requirements and design for new Court Records Management Module is finalized. The latest design documents are sent via e-mail.

**Comment by simmigaba** [comment]
The latest Technical Design document is Updated and is available at below location:
http://sharepoint13vm.cloudapp.net/sites/icc/Documents/ICC%20Website%20Court%20Records%20Management%20System%20v1.docx
