### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by robertocarroll** [robertocarroll/icc-beta#46]
Current big footer acts as sitemap

![08-01_footer](https://cloud.githubusercontent.com/assets/1565953/4355382/41230b86-424b-11e4-8edf-7c25c5e3958b.jpg)

Also provides area to customise links according to user, e.g. these are the top 3 or 5 links across the site that journalists might be interested in: 

![08-02_footer](https://cloud.githubusercontent.com/assets/1565953/4355398/6b61e228-424b-11e4-8ab1-4c77fddb0b18.jpg)

**Comment by simmigaba** [comment]
As discussed with Armin in E-Mail,
Footer section is editable but as HTML content. The Footer is  not a Web Part at the moment but the HTML content for Footer is defined in Master Page (icc.master) present at http://sharepoint13vm.cloudapp.net/sites/icc/_catalogs/masterpage/icc/
So in order to modify the Footer Content, you need to modify the file (icc.master) either using SP designer or by simply downloading/ uploading a new version of file at http://sharepoint13vm.cloudapp.net/sites/icc/_catalogs/masterpage/icc/
