### ISSUE TITLE
Situation - Cases

### ISSUE THREAD

**Issue by robertocarroll** [robertocarroll/icc-beta#55]
![02-03_situation](https://cloud.githubusercontent.com/assets/1565953/4370517/ef09d888-4309-11e4-8b55-33c9a1fdeeb0.jpg)
- Numbers are used on home layout and stage layout in slightly different ways. Design needs consistency.
- Case list pattern is also used on stage layout, but situation (e.g. DRC) is shown instead of stage (e.g. appeals).

**Comment by simmigaba** [comment]
For this section, also we need to address the issue of displaying Multiple defendants for a given Case (Issue #16). The approach can be same as for Case Page i.e. show Multiple defendants images in a Carousel for each Case. Or for this section should we restrict to just show 1st defendant Image (considering that's the main defendant)?. And then when User Clicks on "Case link" then User can see all Defendants on the Case page.

**Comment by robertocarroll** [comment]
I think a single image is better than a carousel on the situation layout. A carousel feels like too much at this point. 

The single image could be a single defendant (is that representative?) or a composite of all defendants (extra work and possibly difficult with many/odd number).

What do you think?

**Comment by simmigaba** [comment]
Yes I was thinking on same lines that "single image is better than a carousel for the Case list on the situation layout". The Defendant Image for this section is really just for representation as User will find complete details for a given Case or Defendant on the Case page. In order to have a configurable solution, I will add a column as "Default" in the back end Defendants Image library for a given Case which will be set to TRUE for a specific Defendant Image and will be displayed as Default Defendant Image for that Case (in Case of Multiple Defendants). And if Website Content Administrators wish to create a Composite Image for a Case in future then they can set Composite Image as "Default" TRUE in the Images Library and WebPart will then automatically display the same.
This will give flexibility for Website Content Creators to decide that which single Image will best represent a given Case. As this single Image can change over the period of time as Cases are Merged/ Split / Renamed etc.

**Comment by simmigaba** [comment]
![image](https://cloud.githubusercontent.com/assets/5706403/5568274/78541fcc-8f7c-11e4-9b0c-1f0f91f7c73e.png)

The list of all Cases is fetched for a given situation and is displayed in descending order of CaseCode i.e. Case with Code ICC-01/04 - 01/06 is displayed first and then Case with Code ICC-01/04 - 01/05 where Case Code is of format ICC-YY/MM - YY/MM

The UI for this WebPart has to be modified as per latest design for beta. Waiting to get latest Situation Page (HTML version) from Kyle so that UI can be modified accordingly.

**Comment by robertocarroll** [comment]
Pointing you to #6 which outlines some requirements about the order. 

In summary: it has to be alphabetical by default, but it would be great if the user could also order by date (i.e. how it is at the moment)

**Comment by simmigaba** [comment]
Changed the logic to sort alphabetical by default. Will look to develop the additional UI option and logic to sort by date.

**Comment by simmigaba** [comment]
Removed all HTML Tables from above WebPart and applied latest HTML div and CSS design as provided by Kyle before. Also added a configuration property for WebPart as "Sort Type" whose value can be "Alphabetical" i.e. sort by Case Name and "Latest" i.e. sort by Case Number (descending). By default Case list is displayed sorted by Case Name.
If later time left, then will also implement the functionality so that website users can also sort Alphabetically or by Latest Case Number directly via Situation Page. Closing the issue for now.
