### ISSUE TITLE
Situation - In the field

### ISSUE THREAD

**Issue by robertocarroll** [robertocarroll/icc-beta#56]
![02-04_situation](https://cloud.githubusercontent.com/assets/1565953/4370538/4fcc65fa-430a-11e4-92b1-69ccaa4f0d67.jpg)
- Here's where a user can see what the ICC's Outreach section is doing in each situation. It's really important content as it shows the ICC's work in countries where it operates.  
- Generic slideshow used for ICC Alpha. Could do with some love. 
- From a dev perspective, it might be useful for a user to see all in the field activity across situations in one place (though not a confirmed requirement), so perhaps implement in a way which can make that easier if possible.

**Comment by simmigaba** [comment]
I believe no further changes are required for this issue in context to beta phase.
This Web Part is implemented using SharePoint out of the box Web Part "Content Query Tool Part" which fetches Images from the Picture Library (/sites/icc/drc/InTheField) at each Situation sub site level. If you want to modify the Image and Content displayed in the Slide Show for drc site then you can modify the same using below URL:
http://sharepoint13vm.cloudapp.net/sites/icc/drc/InTheField/Forms/AllItems.aspx 

The Text displayed for Each Image is fetched from library column "SlideContent".

You can also add new Image to the Slide Show using above library URL. At the the time of Adding, below options are available:
![image](https://cloud.githubusercontent.com/assets/5706403/5567215/b7cf00f2-8f65-11e4-91a5-ef96bf3723f2.png)

At Web Part level, configurable properties are:
Sort by: At the moment Sorting is by Date Created (Ascending)
Number of Items to Display: At the moment this value is 15

Also for this out of the box SlideShow WebPart there is no lazy loading option available. Though we will be applying other options available for performance i.e. 
-- enable the "blob cache" feature which improves performance
-- Use Image Rendition features that creates optimized Images to display

**Comment by simmigaba** [comment]
Instead of  Content Query Tool Part, this WebPart is now implemented as  a Visual WebPart using latest HTML, CSS and Carousel script provided by Kyle. The Images displayed in the SlideShow are fetched from "InTheField" Picture library at Situation site level. The Images are displayed in the SlideShow sorted by Field value "SlideOrder". So you can modify the "SlideOrder" value in underlying Picture Library and accordingly Carousel will display the Images in that Order.
Also every Picture has Field "SlideActive" in underlying Picture Library  where value YES means include in SlideShow and value NO will not display that Image in the SlideShow.
The content displayed in the bottom section of every Image is fetched from value of the Field "SlideContent" in the underlying Picture Library. 

![image](https://cloud.githubusercontent.com/assets/5706403/5735205/4075c5ba-9be8-11e4-956f-20928773b41a.png)
