### ISSUE TITLE
Home - Overview

### ISSUE THREAD

**Issue by robertocarroll** [robertocarroll/icc-beta#59]
![09-01_home](https://cloud.githubusercontent.com/assets/1565953/4370746/57412d04-430d-11e4-90a4-9cf321396850.jpg)
- Same design pattern as the top of the case layout - see #33 
- Featured story on left - the most important thing at the ICC right now.
- News list - latest three news items
- Announcements - short, twitter-like content. Much more regularly updated than news. Used to point users to new things across the site. 
- ICC Alpha feedback - people had trouble distinguishing between "news" (press releases) and "announcements" (shorter, more frequent updates - like Twitter posts). Visual distinction?

**Comment by simmigaba** [comment]
In the existing website, each Press Release Page (ASP Page) is created by PIDS using a Press Release Template. These Press Release Pages are then stored in a centralized Press Releases Pages library and accordingly the list is displayed on main page, at each case and Situation level etc. The press release page will have appropriate content and further links to any Video, other Pages etc. For new public website, we will be using similar Pages library to generate "news" section for Home, Situation, Case, etc pages.

Rob - In existing website, we do not have anything called as Announcements. Can you please provide clarity that what we need to store for each Announcement in backend SP list. I believe it will be: 
- Title
- Publishing Date
- Link (where link can be link to anything regarding which the Announcement is i.e. it can be a link to Press Release Page, A link to Video, etc.) 
- Related To (i.e. Announcement is related to which Case, Situation, Generic etc)
  And accordingly we will fetch latest Announcement data and will display on Home Page, Case Page etc. Do you agree?

Also we do not have any "Announcements" section for Situation pages. Is it intentional? Also I would like to hear final word on below issue to decide if any UI changes are required for "News" and "Announcements" section:
How to make users aware of the difference between news and announcement? #60

**Comment by taslaman** [comment]
It was my understanding that Announcements are form of tweets. We would like to be able to create our own quick information tool with more than 140 characters limit. I would use an SP list for this and the order would be a reverse date/time (newest on top). There would not be a link pointing to the announcement itself.

So the rule would be:
Announcements do not have:
1. title, only the body (content)
2. link pointing to the entry

The body of the announcement would need to be able to contain full HTML, so links, images and so on.

The announcement would need to use the "Related to"  field, so we can show them in different places (Cases, Situations, OTP and so on).

**Comment by simmigaba** [comment]
Thanks. This is clear for me. I believe the overall Announcements design i.e. how we will publish the Announcements to public website, multiple twitter Accounts etc is still under discussion. But independent of that, I can create this centralized Announcements SP list and can implement the WebPart for Home, other pages accordingly.

**Comment by robertocarroll** [comment]
Armin: did you get chance to review the announcements proposal? #60 

Follows the COPE approach - create once, publish everywhere - would be the most efficient and effective way and making it keep within Twitter's 140 characters means it can reach potential users well beyond the limits of the website.

**Comment by taslaman** [comment]
Rob, initially I thought this would be 140 characters items, so I imagined
this being connected to Twitter with the possibility of not posting, but
PIDS wanted to be able to put longer posts. That was the reason behind the
request.

**Comment by simmigaba** [comment]
The implementation details  for this section is as below. Announcement create/ publish discussion will continue as part of Issue #60  

![image](https://cloud.githubusercontent.com/assets/5706403/5823119/2aede7b4-a100-11e4-9793-2d81af02c51f.png)

![image](https://cloud.githubusercontent.com/assets/5706403/5823203/dd1b8aa4-a100-11e4-819c-a69f53d6747f.png)

![image](https://cloud.githubusercontent.com/assets/5706403/6102268/325f4ade-b059-11e4-9c8c-7e54aaeb8d2e.png)
