### ISSUE TITLE
Home - States Parties to the Rome Statute

### ISSUE THREAD

**Issue by robertocarroll** [robertocarroll/icc-beta#64]
![09-07_home](https://cloud.githubusercontent.com/assets/1565953/4370927/dcc08f9a-430f-11e4-9120-fec022055d24.jpg)
- Overview of ASP activity.
- Two featured stories and a list.
- Status of ASP section and place in ICC Beta not yet confirmed.

**Comment by robertocarroll** [comment]
The ASP section will remain as it is on the current site for now: 
http://icc-cpi.int/en_menus/asp/Pages/asp_home.aspx

But we will show the sections on the home layout as in the ICC Alpha: 
- Budget is a title, summary, image and link. Need the ability to update the details but any update will overwrite the previous one. 
- Elections is a title, summary, image and link. Need the ability to update the details but any update will overwrite the previous one. 
- Twelth session is a list of a particular set of documents (which are available within our Sharepoint installation) - Armin: do you have more information on the details?

**Comment by simmigaba** [comment]
Hi Rob - As its decided that ASP section will remain as it is on current site for now. So I will just be adding a new link ("Assembly of State Parties") in the Menus for new public website, clicking on which will open old website link: http://icc-cpi.int/en_menus/asp/Pages/asp_home.aspx "as it is" "in a new tab or window" in browser. Do you agree?
And "Budget" and "Election" sections will be simple Content Editor Web Parts that Web site content Administrators can modify directly.

Armin -- Can you please let me your thoughts if we need to fetch Twelfth session data from SP list of existing website or have to create a new SP list where the appropriate content will be migrated and will be used. In existing website, I believe this info is present in iccdocs library in asp_docs/ASP12 folder. So do we need to fetch latest 3 docs from this folder and display on Home Page for new website?

**Comment by robertocarroll** [comment]
Agree with everything except the new browser window. I think it should be the same browser window.

**Comment by taslaman** [comment]
I was thinking of using the content editor web part for this as well. Not a single file contain any metadata, and it would be more problematic to create anything automatic for this. Now, if this section will always contain those three links pointing to the results of an ASP session, we can easily use the content editor web part, as this only really happens once a year, so updating is now an issue at all.

**Comment by simmigaba** [comment]
Yes State Parties to the ICC Statue -- "Budget" and "Elections" are Content Editor web parts as my understanding is that these will be fairly static and will be directly modified by Content Administrators. But I am not sure about section which shows 3 links for Twelth Session. We can have many documents related to session, example as displayed in below link:
http://icc-cpi.int/en_menus/asp/sessions/documentation/12th-session/Pages/default.aspx

I am not sure on what basis the above 3 links are selected. If these are static links per session then its fine and can be created as Content Editor web part. But to me it looks like latest 3 documents for a given session as present in asp_docs/ASP12  library in existing website. If thats the case then we need to fetch and display these accordingly.
Also I want to know whats the expectation when user clicks on "More" button. Because we are not doing anything related to ASP in beta phase dev so my understanding is that complete ASP section should migrate as it is to new website under content migration phase. So I want to know "More" will re-direct to which URL in the existing website.
Rob - do you want to add anything here.

**Comment by taslaman** [comment]
What I would do is to have three most important documents represented there (we will discuss this withe ASP) and use More to link to http://www.icc-cpi.int/en_menus/asp/sessions/documentation/12th-session/Pages/default.aspx.

**Comment by simmigaba** [comment]
Thanks Armin. Then if idea is to have pre decided links to most important documents which will not change frequently, then I will leave this webpart as content Editor for now which can be directly updated by Content Creators as require.

**Comment by simmigaba** [comment]
As this WebPart will remain a Content Editor, Please find below the HTML files that can be modified in future if you want to modify the content for this WebPart.
State Parties to the ICC Statue: /sites/icc/_catalogs/masterpage/icc/html/home-stateparties.html
Twelth Session: /sites/icc/_catalogs/masterpage/icc/html/home-twelthsession.html
