### ISSUE TITLE
Case - Transcripts

### ISSUE THREAD

**Issue by robertocarroll** [robertocarroll/icc-beta#68]
![01-03_case-1](https://cloud.githubusercontent.com/assets/1565953/4423589/30f88d50-4596-11e4-9bb3-6121def6c7a9.jpg)
- Transcript titles - these have changed from current site. How to import and update?

Simmi: 
"Once data is properly migrated to new website, then stuff like Transcript title etc will automatically be mapped properly as all this info comes from underlying list and libraries of new website."

**Comment by simmigaba** [comment]
Additional requirement to:
-- fetch the data from new centralized document libraries for CRM module
-- display the latest version of Transcript in case multiple versions of same Transcript exists
-- Always show the language of the current site if Transcript in that language is available. If not show the original language

**Comment by simmigaba** [comment]
Hi Rob - During Alpha phase, we had a separate field (Display Title) for Transcripts. E.g. Title = "ICC-01/04-01/06-T-358-ENG CT WT 15-11-2011 1-19 SZ T" and Display Title = "15 November 2011 - Session 358 - Status Conference". And We manually entered the value for Display Title.

Going way forward all the metadata fields for Transcripts will be populated automatically by TRIM-Sharepoint Integration bridge whenever a new Transcript is published and is synch from TRIM to SharePoint Transcript document library. But as DisplayTitle is not maintained as field in TRIM, so we need a programmatic logic to derive the value of Display Tile on the fly.
I believe the first part in Display Title (15 November 2011) is a Publishing Date so that's fine. But I am not able to recall what is meant by the values "Session 358" and "Status Conference" and these values correspond to which metadata fields for Transcript? Because unless we manage these as Metadata fields at each Transcript level, we can not programatically generate a Display Title.

Also Adding Armin to provide his inputs for Transcript display title.
Thanks.

**Comment by simmigaba** [comment]
As per requirements of new CRM module, below functionality is implemented and tested for this web part:
1. Fetch latest Transcripts from centralized Transcripts library ordered by Sequence number (Descending) based on match on Case Name.
2. Fetch only latest Transcripts i.e. latest Corrigenda for a given Sequence number or latest Redaction (or Original) for a given Sequence number
3. Display number of Transcripts as per configurable web part property. At the moment property value is set to 3. 
4. Display the latest Transcript in the site language i.e. if latest Corrigenda is available in both English and French then display the English record if site language is English otherwise display French
5. If latest Transcript is only available in other language then display the same i.e. if latest Corrigenda is only available in French then display the French record if site language is English
6. Display all the latest Court records from Parent Case if the Case has Parent Case (i.e. scenario of Case Split or Case Name change). To display Court records from Parent case, again Points 1-5 above are applicable. 
7. Display all the latest Transcripts from Child Cases if the Case is created after Merging other Cases (i.e. scenario of Case A and Case B Merged into Case C). To display Transcripts from Child cases, again Points 1-5 above are applicable. 
8. The Web part also has another configurable property which takes value as "CourtRecords" or "Transcripts" based on which either latest CourtRecords or Transcripts are displayed. For this webpart set property as "Transcripts".

![image](https://cloud.githubusercontent.com/assets/5706403/5353686/0a1e6528-7fa3-11e4-924b-d8c7def2489e.png)

The open item is still how to generate Display Title for Transcript. This is awaiting feedback from Armin and will now be implemented as part of Sprint 3 Tasks.

**Comment by simmigaba** [comment]
Armin: Transcripts titles: I would recommend the following logic: Date created - Type of session, "Session"+SeqNo. 
Simmi: Could you please let me know how we can get value for “Type of session” (Open Session, Status Conference, etc.) for each Transcript. At the moment this field is not present in the new Transcripts document library nor in any other list/ library for new website. And I am not sure if this field will come from TRIM/ elsewhere or if has to be derived based on some programmatic logic. Please clarify.

**Comment by taslaman** [comment]
Dear Simmi,

Sorry to write about this so late, but we should always have this coming from TRIM. Here is an example metadata extract from a transcript in TRIM:

Container Title: Prosecutor vs. Jean-Pierre Bemba Gombo
Container-Expanded Number: ICC-01/05-01/08
Date Created: 13/1/2011 at 09:37
Related Records: Related to: CR2014/09986: ICC-01/05-01/08-T-46-Red2-FRA WT 13-01-2011 1-60 SZ T
Title: ICC-01/05-01/08-T-46-Red2-ENG CT WT 13-01-2011 1-61 SZ T
Court Document Type: TRANSCRIPT
Date Received: 13/01/2011
Document Number: ICC-01/05-01/08-T-46-Red2-ENG
Interlocutory Appeal: 
Language: ENG - English
Phase of Case: Trial
Source: TC III

Type of Hearing: TRIAL HEARING

HP TRIM URL: http://edms.icc.int/webdrawer/webdrawer.dll/webdrawer/rec/1881820
Reference No: 46
Unique Identifier: 1881820

This is a full extract of the metadata I am currently taking from TRIM in order to generate a full taxonomy based metadata entry per CR on the current website. For a non-transcript CR, the Type of Hearing column is empty.

I hope this answers your question.

Kind regards,
armin.

**Comment by simmigaba** [comment]
Dear Armin - Thanks for your reply. So I understood it correctly then "Type of Session" is same as "Type of Hearing" value that we get from TRIM. I am able to find below set of values for Type of Hearing but there can be more:
Initial Appearance
Motion Hearing
Status Conference
Trial Hearing
Pre Trial Hearing
Appeals Hearing 
Judgement Hearing
Sentence Hearing
COC Hearing

I will then include Type of Hearing value to generate the Transcript Title. Thanks.

**Comment by simmigaba** [comment]
![image](https://cloud.githubusercontent.com/assets/5706403/5707643/72dacff2-9ab0-11e4-8b86-115dbe9af8e2.png)

**Comment by robertocarroll** [comment]
The DateReceived seems unnecessary now that the date is also below. Perhaps it can be removed?

**Comment by simmigaba** [comment]
Agreed. Will remove DateReceived. Thanks.

**Comment by taslaman** [comment]
I agree with this.
