### ISSUE TITLE
Situation - Court records

### ISSUE THREAD

**Issue by robertocarroll** [robertocarroll/icc-beta#69]
![02-02_situation-1](https://cloud.githubusercontent.com/assets/1565953/4423702/3181a47c-4597-11e4-95f0-c8f680e39a84.jpg)

Spitting #54 into three. This one deals with court records only for the situation.

**Comment by simmigaba** [comment]
Additional requirement to:
-- fetch the data from new centralized document libraries for CRM module
-- display the latest version of Court Record (i.e. latest Corrigenda or latest Redaction or Original document if published after Redaction) in case multiple versions of same Court Record exists
-- Always show the language of the current site if Court Record in that language is available. If not show the original language

**Comment by simmigaba** [comment]
As per requirements of new CRM module, below functionality is implemented and tested for this web part:
1. Fetch latest Court Records from centralized Court Records library ordered by Sequence number (Descending) based on match on Situation Name and Case Code is NULL i.e. Court Records only related to Situation.
2. Fetch only latest Court records i.e. latest Corrigenda for a given Sequence number or latest Redaction (or Original) for a given Sequence number
3. Display number of Court records as per configurable web part property. At the moment property value is set to 2. 
4. Display the latest Court Record in the site language i.e. if latest Corrigenda is available in both English and French then display the English record if site language is English otherwise display French
5. If latest Court Record is only available in other language then display the same i.e. if latest Corrigenda is only available in French then display the French record if site language is English
6. The Web part also has another configurable property which takes value as "CourtRecords" or "Transcripts" based on which either latest CourtRecords or Transcripts are displayed. For this webpart set property as "CourtRecords".
![image](https://cloud.githubusercontent.com/assets/5706403/5332079/0386d42e-7e6e-11e4-9fab-f32f64670a55.png)
