### ISSUE TITLE
Situation - Transcripts

### ISSUE THREAD

**Issue by robertocarroll** [robertocarroll/icc-beta#70]
![02-02_situation-2](https://cloud.githubusercontent.com/assets/1565953/4423736/7a93df0e-4597-11e4-8c0f-1b78d78dec75.jpg)

Split #54 to deal with the separate parts.

**Comment by simmigaba** [comment]
Additional requirement to:
-- fetch the data from new centralized document libraries for CRM module
-- display the latest version of Transcript in case multiple versions of same Transcript exists
-- Always show the language of the current site if Transcript in that language is available. If not show the original language

**Comment by simmigaba** [comment]
As per requirements of new CRM module, below functionality is implemented and tested for this web part:
1. Fetch latest Transcripts from centralized Transcripts library ordered by Sequence number (Descending) based on match on Situation Name and Case Code is NULL i.e. Transcripts only related to Situation.
2. Fetch only latest Transcripts i.e. latest Corrigenda for a given Sequence number or latest Redaction (or Original) for a given Sequence number
3. Display number of Transcripts as per configurable web part property. At the moment property value is set to 2. 
4. Display the latest Transcript in the site language i.e. if latest Corrigenda is available in both English and French then display the English record if site language is English otherwise display French
5. If latest Transcript is only available in other language then display the same i.e. if latest Corrigenda is only available in French then display the French record if site language is English
6. The Web part also has another configurable property which takes value as "CourtRecords" or "Transcripts" based on which either latest CourtRecords or Transcripts are displayed. For this webpart set property as "Transcripts".

![image](https://cloud.githubusercontent.com/assets/5706403/5353735/7e71e63e-7fa3-11e4-981b-c64fde5e8376.png)
